apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wvuwz9qk9-go 
  janus-idp.io/tekton: wvuwz9qk9-go
  backstage.io/kubernetes-id: wvuwz9qk9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wvuwz9qk9-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml